USE lab_mysql;

-- Total revenue generated by each salesperson
SELECT s.name, SUM(c.price) AS total_revenue
FROM invoices i
JOIN salespersons s ON i.salesperson = s.id
JOIN cars c ON i.car = c.id
GROUP BY s.name
ORDER BY total_revenue DESC;
